set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "")

set(LLVM_TARGETS_TO_BUILD X86 CACHE STRING "")
#set(LLVM_ENABLE_ASSERTIONS ON CACHE BOOL "")
#set(LLVM_ENABLE_MODULES ON CACHE BOOL "")
set(LLDB_INCLUDE_TESTS OFF CACHE BOOL "")

set(LLDB_NO_INSTALL_DEFAULT_RPATH ON CACHE BOOL "")
set(CMAKE_OSX_DEPLOYMENT_TARGET 10.11 CACHE STRING "")

set(LLDB_BUILD_FRAMEWORK ON CACHE BOOL "")

